version: "3.8"

volumes:
  rabbitmq_data:


networks:
  default:
    external: 
      name: kong_kong-net
      
services:
  
  #################################################
  # Main: The main microservice
  #################################################
  main:
    build:
      context: ./
      dockerfile: main.Dockerfile
    #image: danteliew6/main:1.0
    image: jaredng24/main:1.0
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5555:5555"